version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./production/Dockerfile
    container_name: my-laravel-app
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
  mysql:
    image: mysql:5.7
    container_name: my-mysql-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: