version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-laravel-app
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - mysql
    command: php artisan migrate

  web:
    build:
      context: .
      dockerfile: Dockerfile
      env_file:
        - .env
    container_name: my-web-app
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    container_name: my-mysql-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
      

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=secret

volumes:
  db_data:

